[modbus]
serial_if="/dev/ttyUSB0"
serial_if_baud=19200
serial_if_byte=8
serial_if_par="E"
serial_if_stop=1
slave_addr=1

[pg]
ip = "datenbank.ip"
pguser = "datenbank user"
pgpw = "datenbank pw"
pgport = portnr
db = "datenbankname"
pfad_zu_ssh_auth = "/pfad/zu/ssh_auth.toml"
intervall_daten_senden = 300
dauer_schnellintervall = 120
schnellintervall = 4

[telegram_bot]
token = "telegramtoken"

# Zeit in Sekunden, Was nicht aufgeführt ist, wird nicht ausgelesen
[[messintervall]]
Spannung_L1= 10
Spannung_L2= 10
Spannung_L3= 10
Strom_L1= 5
Strom_L2= 5
Strom_L3= 5
Wirkleistung_L1= 10
Wirkleistung_L2= 10
Wirkleistung_L3= 10
Scheinleistung_L1= 10
Scheinleistung_L2= 10
Scheinleistung_L3= 10
Blindleistung_L1= 10
Blindleistung_L2= 10
Blindleistung_L3= 10
Leistungsfaktor_L1= 10
Leistungsfaktor_L2= 10
Leistungsfaktor_L3= 10
Phasenwinkel_L1= 10
Phasenwinkel_L2= 10
Phasenwinkel_L3= 10
Durchschnittliche_Spannung_zu_N= 300
Durchschnittlicher_Strom_zu_N= 300
aktueller_Gesamtstrom= 10
aktuelle_Gesamtwirkleistung= 10
aktuelle_Gesamtscheinleistung= 10
aktuelle_Gesamtblindleistung= 10
aktueller_Gesamtleistungsfaktor= 10
aktueller_Gesamtphasenwinkel= 10
Frequenz= 10
Import_Wh_seit_reset= 300
Export_Wh_seit_reset= 300
Import_VArh_seit_reset= 300
Export_VArh_seit_reset= 300
VAh_seit_reset= 300
Ah_seit_reset= 300
Gesamtwirkleistung= 999999
Max_Gesamtwirkleistung= 300
Gesamtscheinleistung= 999999
Max_Gesamtscheinleistung= 300
Gesamtstrom_Neutralleiter= 999999
Max_Strom_Neutralleiter= 300
Spannung_L1_L2= 10
Spannung_L2_L3= 10
Spannung_L3_L1= 10
Durchschnittsspannung_L_L= 10
Strom_Neutralleiter= 10
THD_Spannung_L1= 10
THD_Spannung_L2= 10
THD_Spannung_L3= 10
THD_Strom_L1= 10
THD_Strom_L2= 10
THD_Strom_L3= 10
THD_Durchschnittliche_Spannung_zu_N= 10
THD_Durchschnittlicher_Strom_zu_N= 10
Gesamtsystemleistungsfaktor= 10
Strom_L1_demand= 999999
Strom_L2_demand= 999999
Strom_L3_demand= 999999
Max_Strom_L1_demand= 999999
Max_Strom_L2_demand= 999999
Max_Strom_L3_demand= 999999
THD_Spannung_L1_L2= 10
THD_Spannung_L2_L3= 10
THD_Spannung_L3_L1= 10
THD_Durchschnittliche_Spannung_zu_L_L= 10
Total_kwh= 300
Total_kvarh= 300
